name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 设置为你的默认分支
      
# 添加这部分权限配置
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate icons
        run: |
          # 确保目录存在
          mkdir -p icons
          
          # 如果你有源图像，这里可以使用工具转换它
          # 这个示例使用一个简单的 Node.js 脚本来生成基本的占位图标
          cat > generate-icons.js << 'EOL'
          const fs = require('fs');
          
          // 一个非常简单的SVG图标生成器
          function generateIcon(size) {
            return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
              <rect width="100%" height="100%" fill="#4A90E2"/>
              <text x="50%" y="50%" font-family="Arial" font-size="${size/6}" fill="white" text-anchor="middle" dominant-baseline="middle">E-Card</text>
            </svg>`;
          }
          
          // 创建两种尺寸的图标
          fs.writeFileSync('icons/icon-192x192.svg', generateIcon(192));
          fs.writeFileSync('icons/icon-512x512.svg', generateIcon(512));
          
          console.log('SVG icons generated successfully!');
          EOL
          
          # 运行图标生成脚本
          node generate-icons.js
          
          # 安装需要的工具来将SVG转换为PNG
          npm install -g svgexport
          
          # 转换SVG到PNG
          svgexport icons/icon-192x192.svg icons/icon-192x192.png 1x
          svgexport icons/icon-512x512.svg icons/icon-512x512.png 1x
          
          # 删除SVG源文件
          rm icons/*.svg
          
          echo "图标生成完成！"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .   # 部署整个仓库内容
          branch: gh-pages
          clean: true
